### ISSUE TITLE
Lightdm Fails to Obey Conf Files

### ISSUE THREAD

**Issue by moore-bryan** [canonical/lightdm#100]
It was suggested this was a slick-greeter issue, but now it may be a lightdm one; help?

https://github.com/linuxmint/slick-greeter/issues/144

**Comment by robert-ancell** [comment]
The linked issue doesn't indicate any configuration not being used, what specifically is not working?

**Comment by moore-bryan** [comment]
Sorry, I thought the issue was well explained...

slick-greeter version: 1.2.7
Distribution: Solus 4.0
Graphics: Intel® UHD Graphics 620 (Kabylake GT2), 64 bit

I've already set `active-monitor=0` & `display-setup-script=xrandr --output eDP1 --primary` in /etc/lightdm/lightdm.conf and `only-on-monitor=eDP1` in /etc/lightdm/slick-greeter.conf,  but the login screen is still mirrored rather than only showing on my laptop's monitor.

**Comment by robert-ancell** [comment]
active-monitor is not a LightDM option, as noted in the linked issue, so it wont do anything.

Are you sure that display-setup-script is not running the xrandr command? All LightDM can do is run the command you've set - if it's not working properly then the issue is the script is wrong, there is an issue in the X server or the greeter.

**Comment by moore-bryan** [comment]
How would I know if the script isn't being executed properly?

I'm not sure how this is "closed" if it's not resolved; are they two different things?

**Comment by robert-ancell** [comment]
You can look at the logs in /var/log/lightdm to see if the script is being executed. Please re-open if there's evidence it's not.

**Comment by moore-bryan** [comment]
Thanks, @robert-ancell; all three logs in /var/log/lightdm--i.e., lightdm.log, seat0-greeter.log, and x-0.log--show the script never being run.

New ideas?

**Comment by robert-ancell** [comment]
Can you attach the logs to show that? And the exact configuration you are using?

You can also run lightdm --show-config from the command line to show the configuration that LightDM is using.

**Comment by moore-bryan** [comment]
Show-config results:
`bryan@zenbook ~ $ lightdm --show-config
   [LightDM]
D  logind-check-graphical=true

   [Seat:*]
D  session-wrapper=/usr/bin/lightdm-wrapper
E  greeter-session=slick-greeter
F  display-setup-script=/usr/bin/ldm-session-init

   [greeter]
G  background=/usr/share/backgrounds/solus/IMG_0604-solus.JPG
G  theme-name=Arc-Darker
G  icon-theme-name=Arc
G  font-name=Clear Sans 10
G  xft-antialias=true
G  xft-dpi=96
G  xft-hintstyle=full
G  xft-rgba=rgb
G  display-setup-script=xrandr --output eDP1 --primary

Sources:
D  /usr/share/lightdm/lightdm.conf.d/10_solus_default.conf
E  /usr/share/lightdm/lightdm.conf.d/60-slick-greeter.conf
F  /usr/share/lightdm/lightdm.conf.d/99-ldm.conf
D  /usr/share/lightdm/lightdm.conf.d/10_solus_default.conf
E  /usr/share/lightdm/lightdm.conf.d/60-slick-greeter.conf
F  /usr/share/lightdm/lightdm.conf.d/99-ldm.conf
G  /etc/lightdm/lightdm.conf
`

[Uploading seat0-greeter.log.txt…]()
[Uploading lightdm.log.txt…]()

**Comment by robert-ancell** [comment]
So the `--show-config` shows what's happening - you have set `display-setup-script` inside the greeter section, which is not a section that lightdm reads. This is a seat option, which is currently set to `/usr/bin/ldm-session-init`.

**Comment by moore-bryan** [comment]
Any suggestions on how to set that? Is it as "simple" as inserting 
```
[seat]
display-setup-script=xrandr --output eDP1 --primary

```in /etc/lightdm/lightdm.conf?

**Comment by robert-ancell** [comment]
It really depends on what you're trying to do. I suggest you take such a question to forum to ask for help.

**Comment by moore-bryan** [comment]
I'm just trying to have lightdm/slick-greeter only show on one screen when
logging in... I've actually posted in fora & everyone keeps telling me to
report it as a bug and when I do that, everyone suggests it's a distro
issue.

Just looking for an answer... Thank you for your help, though!
