### ISSUE TITLE
Wayland only setup for lightdm

### ISSUE THREAD

**Issue by simon-bueler** [canonical/lightdm#102]
Hi, I wanted to ask if there are intensions on providing a wayland only option, which would not need the xorg wrapper session?

**Comment by robert-ancell** [comment]
You can do this currently. If the greeter and session are Wayland then no X server is started and the default configuration only runs through lightdm-session, which is configured by the distributor.

**Comment by robert-ancell** [comment]
We ran LightDM with Mir only for the Ubuntu Phone and no X server was involved.

**Comment by simon-bueler** [comment]
What would be the configuration to achieve this?
