### ISSUE TITLE
HDPI support

### ISSUE THREAD

**Issue by mondalaci** [canonical/lightdm#113]
Just switched to a 4K monitor which makes the input fields and text displayed by LightDM seem super small. HDPI support would be much welcome.

**Comment by leigh123linux** [comment]
File the issue against the greeter, lightdm doesn't provide any GUI.

**Comment by mondalaci** [comment]
@leigh123linux Thanks, but where do I find the issue tracker of the greeter?

**Comment by leigh123linux** [comment]
@mondalaci 

There are many greeters, you don't say which one you are using.

https://bugs.launchpad.net/lightdm-gtk-greeter

**Comment by mondalaci** [comment]
Thanks for guiding me in the right direction! Just reported the issue in https://github.com/linuxmint/slick-greeter
