### ISSUE TITLE
Question: could the greeter be causing a desktop configuration issue?

### ISSUE THREAD

**Issue by alan12345678** [canonical/lightdm#118]
Hoped I might ask here before I go chasing down rabbit holes:

Been running the Slick Greeter on LightDM for a while now, single user XFCE on top of Arch. No issues at all.

Then two days ago, while experimenting, I installed Openbox and LXQT DE. LOVE IT! However, I have this curious issue now whereby when I log out of e.g. XFCE and into LXQT it seems to carry across all those desktop icons, folders and shortcuts, and combine them with those under LXQT. I delete them.

Then, when I log out of LXQT and back into XFCE it does the same i.e. brings those session icons from LXQR into my XFCE session.

I've asked on both of those forums (naturally) and done what follow up I can in terms of cleaning out session caches, running a few local tests, but despite it will boot correctly (cleanly) just ONE TIME after a clean up, after which this doubling-up problem persists, it suddenly struck me that perhaps the config issue is slightly higher up the chain?

Is there some part of the `$XDG_HOME` spec that the greeter is reading and loading that could be causing these issues? Anything you can suggest I might want to look at?

**Comment by elfring** [comment]
>Anything you can suggest I might want to look at?

Do you observe any desirable effects according to [X session management](https://en.wikipedia.org/wiki/X_session_manager "Description for session management") in your desktop environments?

**Comment by alan12345678** [comment]
thank you for your help. I have however since uninstalled both lightdm and any other DE, so issues were resolved via a different route :)
