### ISSUE TITLE
lightdm breaks kwallet-pam

### ISSUE THREAD

**Issue by tsdgeos** [canonical/lightdm#134]
In kwallet-pam we're create an AF_UNIX socket in /run/user/your_uid/kwallet5.socket and then do a listen() call on it.

This works both in sddm and gdm but on lightdm we're getting errno 95 Operation not supported.

Any idea why this may be happening?

**Comment by natalie-foust** [comment]
[This comment thread seems to explain what's happening here](https://bugs.kde.org/show_bug.cgi?id=400929). I would love for this to be fixed, I've always had this problem while using KDE together with lightdm.
