### ISSUE TITLE
user-authority-in-system-dir=true causes symlink in XAUTHORITY

### ISSUE THREAD

**Issue by mgkuhn** [canonical/lightdm#151]
My `$HOME` resides on an NFS server with "root squash", therefore processes with effective user ID `root(0)` (and thus any application that I run with sudo) cannot access my `~/.Xauthority` file, and as a result sudo or policy-kit rights elevation fail for X11 GUI applications. As a workaround LightDM offers the option
```
  user-authority-in-system-dir=true
```
which I have set with
```
# echo -e '[LightDM]\nuser-authority-in-system-dir=true' \
  >/etc/lightdm/lightdm.conf.d/50-user-authority-in-system-dir.conf
```
As a result LightDM sets up my xauthority file instead at `XAUTHORITY=/var/run/lightdm/$USER/xauthority`, i.e. in a local file system where `euid==0` processes can read it as well.

However, on Ubuntu {16,18,20}.04 `/var/run -> /run` is a symbolic link. As a result, each time I start a snap application (including non-X11 applications!), I get a warning of the form
```
# snap install pdftk
$ pdftk
2018/08/24 17:32:48.267771 cmd_run.go:442: WARNING: XAUTHORITY
environment value is not a clean path: "/run/lightdm/mgk25/xauthority"
```
I don't know why snap applications worry about symbolic links in the XAUTHORITY path (see https://bugs.launchpad.net/snapd/+bug/1902250 ). But since they do: would it possible for you to change the XAUTHORITY path set by `user-authority-in-system-dir=true` such that it does not contain a symbolic link on Ubuntu installations?

In fact, since systemd now creates a nice per-user tmp file system in `XDG_RUNTIME_DIR=/run/user/$UID` wouldn't `XAUTHORITY=$XDG_RUNTIME_DIR/xauthority` be a much better default place for the xauthority file?

See also https://bugs.launchpad.net/ubuntu/+source/lightdm/+bug/1648107

**Comment by Alexander-Shukaev** [comment]
I resolved that issue with the following standalone profile script `/etc/profile.d/01-Xauthority.sh`:

```shell
#!/bin/sh
##
realpath() (
  path="${1}"
  while [ -L "${path}" ]; do
    dir="${path%/*}"
    if [ "${dir}" = "${path}" ]; then
      dir='.'
    fi
    CDPATH= command cd -- "${dir}/" || return "${?}"
    path="${path##*/}"
    path="$(command readlink "${path}")" || return "${?}"
  done
  dir="${path%/*}"
  if [ "${dir}" = "${path}" ]; then
    dir='.'
  fi
  CDPATH= command cd -- "${dir}/" || return "${?}"
  dir="$(command pwd -P)" || return "${?}"
  dir="${dir%/}"
  path="${path##*/}"
  if   [ "${path}" = '.'  ]; then
    path=
  elif [ "${path}" = '..' ]; then
    dir="${dir%/*}"
    path=
  fi
  command echo "${dir:-/}${path:+${dir:+/}}${path}"
)
##
if [ -n "${XAUTHORITY-}" ]; then
  if _path="$(realpath "${XAUTHORITY}")" && [ -n "${_path}" ]; then
    XAUTHORITY="${_path}"
  fi
  unset -v _path
  ##
  export XAUTHORITY
fi
##
unset -f realpath
```

**Comment by mgkuhn** [comment]
Having now looked in https://bugs.launchpad.net/snapd/+bug/1902250 further at the code in snapd that objects to symlinks in the $XAUTHORITY path, I am now convinced that snapd does it wrong and that the snapd authors should change their code such that they read the Xauthority file with the euid of the user, rather than trying to read it as root and manually check for all kinds of security risks that this might create, including the presence of symlinks. That will make their code simpler, more secure and cause fewer usability problems (including this one).

So I'm closing this ticket, as this is really something that needs to be fixed on the snapd side.
