### ISSUE TITLE
autologin is not working every time

### ISSUE THREAD

**Issue by logan001** [canonical/lightdm#191]
I'm on archlinux with cinnamon DE. 
Sometimes after 2-4 restarts i get the login screen. 
i'm not sure if this is a bug of lightdm or is the OS (arch in this case) that screws the autologin.

**Comment by adrelanos** [comment]
Same issues.

**Comment by logan001** [comment]
i'll close this issue. i don't know when it stop bugging me but for at least 3 months i had no issue with autologin
