### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by paulmenzel** [canonical/lightdm#193]
The last release 1.30.0 is from May 2019. It’d be great if you could cut a new release, so distributions following releases can pick it up easily.

**Comment by Apteryks** [comment]
@paulmenzel  1.32 is out, this can be closed :-)

**Comment by paulmenzel** [comment]
Fixed by commit https://github.com/canonical/lightdm/commit/4b10d07b7bf87668a245b438b5ffc82e3956bd1c.

Release 1.32.0: https://github.com/canonical/lightdm/releases/tag/1.32.0
