### ISSUE TITLE
Does lightdm use systemd to get dbus connection?

### ISSUE THREAD

**Issue by Gymxo** [canonical/lightdm#194]
The reason why I ask is that while trying to run this on ios(which is a darwin platform and uses launchd), I seem to get failed to connect to dbus. Running with dbus-services=false leads to an error of G_IS_OBJECT.  
![NWXL2862](https://user-images.githubusercontent.com/55960119/119142322-5c903900-ba14-11eb-905c-e5a85fa30579.PNG)
![IZKD9125](https://user-images.githubusercontent.com/55960119/119142323-5d28cf80-ba14-11eb-94c9-c1060c627aa7.PNG)

**Comment by robert-ancell** [comment]
LightDM uses D-Bus for communication with system services (e.g. logind). It doesn't require systemd. I would say it's never really been tested without D-Bus, so you're likely to hit an assertion/bug.

**Comment by Gymxo** [comment]
Thanks for the reply
