### ISSUE TITLE
Login Screen Banner message

### ISSUE THREAD

**Issue by jcpunk** [canonical/lightdm#221]
Our site requires posting of the terms/conditions/usage policy on the system login screen.

It appears the lightdm doesn't have a way to post a banner message on the login screen.

This feature exists in other login managers, for example GDM:
https://help.gnome.org/admin/system-admin-guide/stable/login-banner.html.en

**Comment by qwertychouskie** [comment]
This bug should probably be filed with the particular greeter your are using, as they are usually responsible for visual/layout/buttons/text/etc.  (As a band-aid, you could also just bake the text into the background image.)

**Comment by robert-ancell** [comment]
Correct, this is a greeter feature so doesn't require any special work in LightDM. You could potentially have a configuration option that could be used by any greeters, but you will probably get a better experience with this configured in the greeter (so can use markup / layout etc).
