### ISSUE TITLE
Latest main segfaults on startup

### ISSUE THREAD

**Issue by AdrianVovk** [canonical/lightdm#259]
I'm experiencing segfaults on the latest main commit (fe117f0), and it looks like the issue is coming from [here](https://github.com/canonical/lightdm/blob/fe117f0/src/lightdm.c#L816). If I had to guess, this was supposed to be `config_set_boolean` instead of `config_set_string`?

**Comment by robert-ancell** [comment]
Fixed in 3fd8d5c0d909d4b7e8cab285a08410796cc69e69
