### ISSUE TITLE
deb package doesn't build...

### ISSUE THREAD

**Issue by Creteil** [canonical/lightdm#260]
The deb package doesn't build properly :

```
make[3]: Leaving directory '/home/bigbob/tmp/Building/lightdm/lightdm/help'
make[2]: Leaving directory '/home/bigbob/tmp/Building/lightdm/lightdm/help'
make[2]: Entering directory '/home/bigbob/tmp/Building/lightdm/lightdm'
make[3]: Entering directory '/home/bigbob/tmp/Building/lightdm/lightdm'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/bigbob/tmp/Building/lightdm/lightdm'
make[2]: Leaving directory '/home/bigbob/tmp/Building/lightdm/lightdm'
make[1]: Leaving directory '/home/bigbob/tmp/Building/lightdm/lightdm'
   debian/rules override_dh_install
make[1]: Entering directory '/home/bigbob/tmp/Building/lightdm/lightdm'
rm -r debian/tmp/usr/share/help/C/
# we do install pam through installpam and init through installinit
dh_install -X.a -X.la -Xpam.d -X'etc/init/lightdm.conf' --fail-missing
dh_install: warning: Compatibility levels before 10 are deprecated (level 9 in use)
dh_install: warning: Please use dh_missing --list-missing/--fail-missing instead
dh_install: warning: This feature will be removed in compat 12.
dh_install: warning: Cannot find (any matches for) "etc/dbus-1/" (tried in ., debian/tmp)

dh_install: warning: lightdm missing files: etc/dbus-1/
dh_install: error: missing files, aborting
make[1]: *** [debian/rules:28: override_dh_install] Error 255
make[1]: Leaving directory '/home/bigbob/tmp/Building/lightdm/lightdm'
make: *** [debian/rules:6: binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
bigbob@bigbob-UX331UN:~/tmp/Building/lightdm/lightdm$
```

Do you have any hint to fix it ?

**Comment by rezso** [comment]
Remove etc/dbus-1 from debian/lightdm.install file: etc/dbus-1

**Comment by Creteil** [comment]
Thanks, that worked !!!

BEFORE
AFTER

<pre style="color:#000020;background:#f6f8ff;">bigbob@bigbob<span style="color:#308080; ">-</span>UX331UN<span style="color:#308080; ">:</span><span style="color:#308080; ">~</span>$ dpkg <span style="color:#308080; ">-</span>l liblightdm<span style="color:#308080; ">-</span>gobject<span style="color:#308080; ">-</span><span style="color:#008c00; ">1</span><span style="color:#308080; ">-</span><span style="color:#008c00; ">0</span> lightdm
Souhait<span style="color:#308080; ">=</span>inconnU<span style="color:#308080; ">/</span>Installé<span style="color:#308080; ">/</span>suppRimé<span style="color:#308080; ">/</span>Purgé<span style="color:#308080; ">/</span>H<span style="color:#308080; ">=</span>à garder
<span style="color:#308080; ">|</span> État<span style="color:#308080; ">=</span>Non<span style="color:#308080; ">/</span>Installé<span style="color:#308080; ">/</span>fichier<span style="color:#308080; ">-</span>Config<span style="color:#308080; ">/</span>dépaqUeté<span style="color:#308080; ">/</span>échec<span style="color:#308080; ">-</span>conFig<span style="color:#308080; ">/</span>H<span style="color:#308080; ">=</span>semi<span style="color:#308080; ">-</span>installé<span style="color:#308080; ">/</span>W<span style="color:#308080; ">=</span>attend<span style="color:#308080; ">-</span>traitement<span style="color:#308080; ">-</span>déclenchements
<span style="color:#308080; ">|</span><span style="color:#308080; ">/</span> Err<span style="color:#308080; ">?</span><span style="color:#308080; ">=</span><span style="color:#308080; ">(</span>aucune<span style="color:#308080; ">)</span><span style="color:#308080; ">/</span>besoin Réinstallation <span style="color:#308080; ">(</span>État<span style="color:#008c00; ">,</span>Err<span style="color:#308080; ">:</span> majuscule<span style="color:#308080; ">=</span>mauvais<span style="color:#308080; ">)</span>
<span style="color:#308080; ">|</span><span style="color:#308080; ">|</span><span style="color:#308080; ">/</span> Nom                          Version                 Architecture Description
<span style="color:#308080; ">+</span><span style="color:#308080; ">+</span><span style="color:#308080; ">+</span><span style="color:#308080; ">-</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">-</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">-</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">-</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span>
ii  liblightdm<span style="color:#308080; ">-</span>gobject<span style="color:#308080; ">-</span><span style="color:#008c00; ">1</span><span style="color:#308080; ">-</span><span style="color:#008c00; ">0</span><span style="color:#308080; ">:</span>amd64 <span style="color:#008c00; ">1.30</span><span style="color:#008c00; ">.0</span><span style="color:#308080; ">-</span>0ubuntu4<span style="color:#008c00; ">.21</span><span style="color:#008c00; ">.10</span><span style="color:#008c00; ">.1</span> amd64        LightDM GObject client library
ii  lightdm                      <span style="color:#008c00; ">1.30</span><span style="color:#008c00; ">.0</span><span style="color:#308080; ">-</span>0ubuntu4<span style="color:#008c00; ">.21</span><span style="color:#008c00; ">.10</span><span style="color:#008c00; ">.1</span> amd64        Display Manager
bigbob@bigbob<span style="color:#308080; ">-</span>UX331UN<span style="color:#308080; ">:</span><span style="color:#308080; ">~</span>$ dpkg <span style="color:#308080; ">-</span>l liblightdm<span style="color:#308080; ">-</span>gobject<span style="color:#308080; ">-</span><span style="color:#008c00; ">1</span><span style="color:#308080; ">-</span><span style="color:#008c00; ">0</span> lightdm
Souhait<span style="color:#308080; ">=</span>inconnU<span style="color:#308080; ">/</span>Installé<span style="color:#308080; ">/</span>suppRimé<span style="color:#308080; ">/</span>Purgé<span style="color:#308080; ">/</span>H<span style="color:#308080; ">=</span>à garder
<span style="color:#308080; ">|</span> État<span style="color:#308080; ">=</span>Non<span style="color:#308080; ">/</span>Installé<span style="color:#308080; ">/</span>fichier<span style="color:#308080; ">-</span>Config<span style="color:#308080; ">/</span>dépaqUeté<span style="color:#308080; ">/</span>échec<span style="color:#308080; ">-</span>conFig<span style="color:#308080; ">/</span>H<span style="color:#308080; ">=</span>semi<span style="color:#308080; ">-</span>installé<span style="color:#308080; ">/</span>W<span style="color:#308080; ">=</span>attend<span style="color:#308080; ">-</span>traitement<span style="color:#308080; ">-</span>déclenchements
<span style="color:#308080; ">|</span><span style="color:#308080; ">/</span> Err<span style="color:#308080; ">?</span><span style="color:#308080; ">=</span><span style="color:#308080; ">(</span>aucune<span style="color:#308080; ">)</span><span style="color:#308080; ">/</span>besoin Réinstallation <span style="color:#308080; ">(</span>État<span style="color:#008c00; ">,</span>Err<span style="color:#308080; ">:</span> majuscule<span style="color:#308080; ">=</span>mauvais<span style="color:#308080; ">)</span>
<span style="color:#308080; ">|</span><span style="color:#308080; ">|</span><span style="color:#308080; ">/</span> Nom                          Version      Architecture Description
<span style="color:#308080; ">+</span><span style="color:#308080; ">+</span><span style="color:#308080; ">+</span><span style="color:#308080; ">-</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">-</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">-</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">-</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span><span style="color:#308080; ">=</span>
ii  liblightdm<span style="color:#308080; ">-</span>gobject<span style="color:#308080; ">-</span><span style="color:#008c00; ">1</span><span style="color:#308080; ">-</span><span style="color:#008c00; ">0</span><span style="color:#308080; ">:</span>amd64 <span style="color:#008c00; ">1.32</span><span style="color:#008c00; ">.0</span>       amd64        LightDM GObject client library
ii  lightdm                      <span style="color:#008c00; ">1.32</span><span style="color:#008c00; ">.0</span>       amd64        Display Manager
bigbob@bigbob<span style="color:#308080; ">-</span>UX331UN<span style="color:#308080; ">:</span><span style="color:#308080; ">~</span>$
</pre>
