### ISSUE TITLE
Log in without pressing the enter key when fprint recognizes the fingerprint

### ISSUE THREAD

**Issue by Photon89** [canonical/lightdm#277]
Hi, I am using Manjaro Linux on a laptop which has a fingerprint reader. After putting my finger onto it, LightDM lets me in, but only after pressing the Enter button. Is it possible to trigger the login without pressing the button, just by putting the finger onto the fingerprint reader?

Thanks!

**Comment by sch1ag** [comment]
> Hi, I am using Manjaro Linux on a laptop which has a fingerprint reader. After putting my finger onto it, LightDM lets me in, but only after pressing the Enter button. Is it possible to trigger the login without pressing the button, just by putting the finger onto the fingerprint reader?
> 
> Thanks!

Hello @Photon89 !

I have the same issue with Ubuntu 22.04.2 LTS (Jammy Jellyfish).
Have you found a solution?

Thanks!

**Comment by Photon89** [comment]
@sch1ag Nope, still stuck with it, I just do press the enter key for now...

**Comment by qwertychouskie** [comment]
This sounds more like an issue with the greeter you are using, not LightDM itself.  This issue should probably be closed, and issues opened with the greeters in question (e.g. https://github.com/Xubuntu/lightdm-gtk-greeter).

**Comment by Photon89** [comment]
This has been mentioned at, so I'm closing here: https://github.com/Xubuntu/lightdm-gtk-greeter/issues/140
