### ISSUE TITLE
login only works on 2nd try

### ISSUE THREAD

**Issue by junghans** [canonical/lightdm#291]
This is a stock Fedora 37 install with xfce. After a reboot the first login will always fail and then 2nd try will work.
(see https://bugzilla.redhat.com/show_bug.cgi?id=2167386)

Looking at the difference in `lightdm.log` (success) vs `light.log.old` (failed), the only real different is:
```diff
--- lightdm.log 2023-02-08 18:46:09.056295101 -0700
+++ lightdm.log.old     2023-02-08 18:46:09.057295116 -0700
@@ -59,20 +61,25 @@
 DEBUG: Authenticate result for user user: Success
 DEBUG: User user authorized
 DEBUG: Greeter sets language en_US.utf8
-DEBUG: Greeter requests session xfce
-DEBUG: Seat seat0: Stopping greeter; display server will be re-used for user session
-DEBUG: Terminating login1 session c2
-DEBUG: Session pid=1234: Sending SIGTERM
 DEBUG: Greeter closed communication channel
+DEBUG: Session pid=1234: Exited with return value 1
+DEBUG: Seat seat0: Session stopped
+DEBUG: Seat seat0: Stopping; failed to start a greeter
+DEBUG: Seat seat0: Stopping
+DEBUG: Seat seat0: Stopping display server
+DEBUG: Sending signal 15 to process 3321
+DEBUG: Seat seat0: Stopping session
 DEBUG: Session pid=1234: Exited with return value 0
 DEBUG: Seat seat0: Session stopped
```

Any ideas what is going wrong here?

**Comment by leigh123linux** [comment]
Maybe the greeter app is broken.

```
[+15.54s] DEBUG: Authenticate result for user leigh: Success
[+15.54s] DEBUG: User leigh authorized
[+15.54s] DEBUG: Greeter requests session cinnamon
[+15.54s] DEBUG: Seat seat0: Stopping greeter; display server will be re-used for user session
[+15.54s] DEBUG: Terminating login1 session c1
[+15.54s] DEBUG: Session pid=916: Sending SIGTERM
[+15.56s] DEBUG: Greeter closed communication channel
[+15.56s] DEBUG: Session pid=916: Exited with return value 0
[+15.56s] DEBUG: Seat seat0: Session stopped
[+15.56s] DEBUG: Seat seat0: Greeter stopped, running session
[+15.56s] DEBUG: Registering session with bus path /org/freedesktop/DisplayManager/Session0
[+15.56s] DEBUG: Session pid=984: Running command /etc/X11/xinit/Xsession cinnamon-session-cinnamon
[+15.56s] DEBUG: Creating shared data directory /var/lib/lightdm-data/leigh
[+15.56s] DEBUG: Session pid=984: Logging to .xsession-errors
[+16.07s] DEBUG: Activating VT 1
[+16.07s] DEBUG: Activating login1 session 2
[+16.07s] DEBUG: Seat seat0 changes active session to 
[+16.07s] DEBUG: Seat seat0 changes active session to 2
[+16.07s] DEBUG: Session 2 is already active
```

I use slick-greeter

**Comment by knob-creek** [comment]
The same happens here, but only on one PC (with slick-greeter), every other PC around just works as expected, with the gtk greeter as well as with the slick greeter.  It still happens with Fedora 38.
Analysing the logs shows that the X11 and xfce scripts cannot communicate with the X server (or there is no X server).  This is why starting the xfce session fails with exit code 1.

Adding a loop into one of the X11 scripts never succeeds, so no X server ever shows up while the session tries to start.

**Comment by leigh123linux** [comment]
IMO it's the session that should start X or Wayland, it isn't lightdm's job to start it.

**Comment by knob-creek** [comment]
This might be an explanation and a solution:

- On the machine in question, the host name changes _after_ lightdm is started.
- This might have X reject connections from processes started with a different host name than the one X itself was started with.
- Solution would be: don't change the host name after lightdm was started, or, start lightdm only after the host name is settled.

What i did:
- Enter a matching host name into `/etc/hostname`.
- Start lightdm _after_ `systemd-hostnamed.service` by adding an appropriate line to `/lib/systemd/system/lightdm.service`.

The latter might be adopted by the distributions.

**Comment by junghans** [comment]
I can confirm entering a hostname in `/etc/hostname` works!

**Comment by raveit65** [comment]
I really like to see an upstream PR or commit before we add this to fedora.

**Comment by junghans** [comment]
@raveit65 The `lightdm.service` files are distribution specific, but #336 has the fix suggested by @knob-creek in https://github.com/canonical/lightdm/issues/291#issuecomment-1834402939.

**Comment by raveit65** [comment]
> @raveit65 The `lightdm.service` files are distribution specific, but #336 has the fix suggested by @knob-creek in [#291 (comment)](https://github.com/canonical/lightdm/issues/291#issuecomment-1834402939) for Debian at least.

Well, the file is inside the debian folder because of the structure of debian packaging for debian and his derivatives.
But it is definitely the same file for all distros which use systemd. For me this is an upstream task.

**Comment by junghans** [comment]
> > @raveit65 The `lightdm.service` files are distribution specific, but #336 has the fix suggested by @knob-creek in [#291 (comment)](https://github.com/canonical/lightdm/issues/291#issuecomment-1834402939) for Debian at least.
> 
> Well, the file is inside the debian folder because of the structure of debian packaging for debian and his derivatives. But it is definitely the same file for all distros which use systemd. For me this is an upstream task.

Unfortunately not, Fedora at least ships their own service file: https://src.fedoraproject.org/rpms/lightdm/blob/rawhide/f/lightdm.service

**Comment by raveit65** [comment]
> > > @raveit65 The `lightdm.service` files are distribution specific, but #336 has the fix suggested by @knob-creek in [#291 (comment)](https://github.com/canonical/lightdm/issues/291#issuecomment-1834402939) for Debian at least.
> > 
> > 
> > Well, the file is inside the debian folder because of the structure of debian packaging for debian and his derivatives. But it is definitely the same file for all distros which use systemd. For me this is an upstream task.
> 
> Unfortunately not, Fedora at least ships their own service file: https://src.fedoraproject.org/rpms/lightdm/blob/rawhide/f/lightdm.service

Doesn't matter, i'd like to hear an upstream comment about this issue and adding `systemd-hostnamed.service` to after sequence.

**Comment by wallentx** [comment]
Reading this thread has helped me understand that the lightdm.service files end up being distro specific.. In another project, I [implemented a LightDM failsafe handler](https://github.com/LukeShortCloud/winesapOS/commit/5d9b78c312ffe6073e7e3e9ad737f7252defacc0) to address a scenario where xorg could fail to start. I mentioned this here https://github.com/canonical/lightdm/issues/337 today.

If this isn't a thing that would be implemented here, and persist to other distros, perhaps the failsafe might be an easy-to-implement & most-basic method of handling a LightDM failure for other distributions?
If LightDM fails to launch X/wayland/whatever, pop me back to a TTY with a hint so I can fix it. That seems like an ideal state.

**Comment by raveit65** [comment]
This issue is reproducible on debian and his derivates and fedora (redhat rpm family) systems.
That means it is related to all systemd distros and should be first fixed from upstream here, than upstream maintainers can follow.
It doesn't matter if downstream systemd unit files can be different.
We need to know from upstream maintainer that adding `systemd-hostnamed.service` to unit file is the right fix.
