### ISSUE TITLE
Lightdm does not start session on kernels without TTY and VT support

### ISSUE THREAD

**Issue by twaik** [canonical/lightdm#31]
Trying to use lightdm on debian on kernel without TTY and VT. Loginctl reports no sessions. 
Error: Jul 15 15:27:34 okt lightdm[2605]: pam_systemd(lightdm-autologin:session): Failed to create session: Seat has no VTs but VT number not 0

**Comment by robert-ancell** [comment]
Does it work if you set the following in lightdm.conf?

```[LightDM]
minimum-vt=7```

Do you know how LightDM can detect you have a kernel without VT support?

**Comment by twaik** [comment]
> Do you know how LightDM can detect you have a kernel without VT support?
`ioctl VT_GETSTATE: Invalid argument`.
> Does it work if you set the following in lightdm.conf
I have no device to test that conf, I'll ask my friend.

**Comment by twaik** [comment]
Stale issue.
