### ISSUE TITLE
LightDM interferes with X/XFCE on Arch with kernel 6.4

### ISSUE THREAD

**Issue by PMKielstra** [canonical/lightdm#311]
When I create a new Arch install in a VM and install xorg-server, xfce4, and lightdm, everything works as intended with kernel 6.3.9.  However, when I update to kernel 6.4.1 and do the same, lightdm just gives me a black screen.  Furthermore, if I break out of lightdm by choosing a new tty (ctrl+alt+f2), log in through the terminal, and try to run xfce4 by editing ~/.xinitrc and running startx, I just get a black screen there too.  Switching back to the linux-lts kernel (6.1) fixes the issue.

**Comment by qwertychouskie** [comment]
The Linux kernel has a policy to never break userspace, so if a kernel update broke userspace, that's a kernel bug.  Submit your bug at https://bugzilla.kernel.org/
