### ISSUE TITLE
Is there a way to disable topbar in greeter via .conf files? (or any other way)

### ISSUE THREAD

**Issue by Lucksinia** [canonical/lightdm#317]
Hi.
I am contemplating on how to do it... And couldn't find it. 
Before, there was greeter.ui , which could be modified... but that was really long time ago.
Is there a way right now?

**Comment by qwertychouskie** [comment]
You should open this issue with whatever greeter you are using (e.g. https://github.com/Xubuntu/lightdm-gtk-greeter).  lightdm the display server doesn't provide any UI AFAIK.

**Comment by Lucksinia** [comment]
Okay, yea, thanks. It's just... I was under the impression that lightdm devs have guidelines on this stuff. (On how to modify layout and exetra...)
