### ISSUE TITLE
Build failure with 64b time_t on 32b arches

### ISSUE THREAD

**Issue by corsac-s** [canonical/lightdm#352]
Hi,

Debian (and Ubuntu) is currently migrating to time64 for the year 2039 issue. Apparently that makes LightDM fails to build on 32b architectures with the following error:

```/bin/bash ../../libtool  --tag=CC   --mode=link gcc -Wall
-Wstrict-prototypes                  -Wnested-externs
-Werror=missing-prototypes                  -Werror=implicit-function-
declaration                  -Werror=pointer-arith
-Werror=init-self                  -Werror=format-security
-Werror=format=2                  -Werror=missing-include-dirs
-I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabi/glib-2.0/include
-I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabi/glib-2.0/include
-I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabi/glib-2.0/include -pthread
-I/usr/include/libmount -I/usr/include/blkid  -I/usr/include/gio-unix-2.0
-I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabi/glib-2.0/include -pthread
-I/usr/include/libmount -I/usr/include/blkid  -g -O2 -Werror=implicit-function-
declaration -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong
-fstack-clash-protection -Wformat -Werror=format-security -O0  -Wl,-z,relro
-Wl,-z,now -Wl,-O1 -o Xvnc Xvnc-Xvnc.o Xvnc-x-authority.o Xvnc-x-common.o Xvnc-
x-server.o Xvnc-status.o -lgobject-2.0 -lglib-2.0  -lglib-2.0  -lgio-2.0
-lgobject-2.0 -lglib-2.0  -lgio-2.0 -lgobject-2.0 -lglib-2.0
/tmp/ccCHYR2t.s: Assembler messages:
/tmp/ccCHYR2t.s:2779: Error: symbol `open64' is already defined
/tmp/ccCHYR2t.s:3181: Error: symbol `creat64' is already defined
/tmp/ccCHYR2t.s:3508: Error: symbol `__stat64_time64' is already defined```

The full build (on 32b arm) is here:

https://buildd.debian.org/status/fetch.php?pkg=lightdm&arch=armel&ver=1.32.0-4%2Bb3&stamp=1711185127&raw=0

The downstream bug is here:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1067561

Ubuntu apparently used the following patch:

```--- a/tests/src/libsystem.c
+++ b/tests/src/libsystem.c
@@ -1,6 +1,9 @@
 #define _GNU_SOURCE
 #define __USE_GNU

+#undef _FILE_OFFSET_BITS
+#undef _TIME_BITS
+
 #include <config.h>

 #include <stdlib.h>```

but it looks a bit strong to me so I'd welcome some upstream comment on this.

**Comment by robert-ancell** [comment]
I don't know what's going on here exactly, but it seems like something has changed in the way these functions that LightDM is mocking are defined. I don't know why the undefs avoids this - I hope there is a cleaner way of doing this.

**Comment by corsac-s** [comment]
Hey, Peter Green provided more details on the Debian bug, copy-pasted here:

> My understanding of the issue.
> 
> In glibc _FILE_OFFSET_BITS=64 is used to substitute the standard file
> handling types and functions with versions that use 64-bit file
> offsets. Similarly _TIME_BITS=64 is used to susbstitute time handling
> types and functions with versions that use 64-bit seconds counts.
> 
> All of this only applies to 32-bit architectures, on 64-bit
> architectures the default types in glibc are 64-bit.
> 
> The "time64" transition was implemented by defining _TIME_BITS=64 and
> _FILE_OFFSET_BITS=64 by default in both dpkg-buildflags and the compiler.
> 
> That's fine for normal code, but tests/src/libsystem.c is not normal
> code, it's a file of "test mocks" that override functions in glibc
> for testing purposes. If _FILE_OFFSET_BITS=64 is defined, it ends up
> trying to override "open64" twice, rather than trying to override both
> "open" and "open64"
> 
> If we undef _FILE_OFFSET_BITS then we must also undef _TIME_BITS,
> otherwise the glibc headers will refuse to compile.
> 
> So the patch seems reasonable to me, and since this is only test
> code, it appears to be pretty low risk. We would appreciate having
> this fix in unstable so the time_t transition can move forward.
> 
Hope that helps

**Comment by robert-ancell** [comment]
Looking at the headers, does the following not resolve this clearer? I don't have any 32 bit architecture handy to test it on.

```
diff --git a/tests/src/libsystem.c b/tests/src/libsystem.c
index 4007ab49..513395a7 100644
--- a/tests/src/libsystem.c
+++ b/tests/src/libsystem.c
@@ -266,6 +266,7 @@ open_wrapper (const char *func, const char *pathname, int flags, mode_t mode)
     return _open (new_path, flags, mode);
 }
 
+#ifndef __USE_FILE_OFFSET64
 int
 open (const char *pathname, int flags, ...)
 {
@@ -279,6 +280,7 @@ open (const char *pathname, int flags, ...)
     }
     return open_wrapper ("open", pathname, flags, mode);
 }
+#endif
 
 int
 open64 (const char *pathname, int flags, ...)
```

**Comment by plugwash** [comment]
As well as the "open" mock, the "stat" and "creat" mocks have the same issue

I was able to successfully build the Debian lightdm package with the attached patch, based on extending the concept of your patch to these additional functions.

[10_fix-mock-build-on-time64.patch.txt](https://github.com/canonical/lightdm/files/15029228/10_fix-mock-build-on-time64.patch.txt)
