### ISSUE TITLE
Potential security issue: bypassing LightDM lockscreen through secondary display.

### ISSUE THREAD

**Issue by Jonathan-Kamphuis** [canonical/lightdm#69]
I have found that if i have my laptop in sleepmode, i can wake it up by lifting up the laptop-lid and then if i connect a monitor through HDMI when it is in the process of waking up the secondary screen will be fully accessible by mouse.
I can switch (Browser) tabs, access the desktop and basically look at anything that is currently open on the display connected through the HMDI.

**Comment by robert-ancell** [comment]
LightDM doesn't provide a lockscreen, so this is either a greeter or shell issue.
