### ISSUE TITLE
Incorrect password when account will lock automatically

### ISSUE THREAD

**Issue by hasanparasteh** [canonical/lightdm#82]
OS : Ubuntu 19.04
lightdm: 1.28.0

Description:
I am using 2 language input for my operating system! The first one is English the second is Persian. When I change the input source to Persian and the computer sleeps then the lightdm wont let me unlock the computer and tells me the password is incorrect but the password I typed was correct. I realized that when I type password the text field is in RTL mode but the language in the lightdm box was selected en!

I think it's somehow a bug in light display manager.Can you please review and check if there is any bug here cause I have this problem in my system.

**Comment by lukelex** [comment]
I'm experiencing the same. Did you ever find out the problem?
